# Per-developer vi-agent instance
# Generated by create-instance.sh — do not edit manually
# Developer: __DEV_NAME__
# Slot: __SLOT__

name: vi-agent-__DEV_NAME__

services:
  api-server:
    build:
      context: /opt/vi-agent/repo/api-server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "__API_PORT__:8000"
    environment:
      - POSTGRES_USER=vi___DEV_NAME__
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=vi___DEV_NAME__
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://:${REDIS_PASSWORD}@host.docker.internal:6379/0
      - REDIS_PREFIX=__DEV_NAME__:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRE_MINUTES=1440
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_BASE_URL=http://host.docker.internal:__API_PORT__
      - CORS_ORIGINS=http://${SERVER_IP}:__FRONTEND_PORT__,http://localhost:__FRONTEND_PORT__
      - INTERNAL_API_TOKEN=${INTERNAL_API_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 384M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: /opt/vi-agent/repo/frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://${SERVER_IP}:__API_PORT__
        - VITE_LIVEKIT_URL=${LIVEKIT_URL}
    restart: unless-stopped
    ports:
      - "__FRONTEND_PORT__:80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 192M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  vi-gateway:
    build:
      context: /opt/vi-agent/repo/gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "__GATEWAY_PORT__:18789"
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - API_BASE_URL=http://host.docker.internal:__API_PORT__
      - INTERNAL_API_TOKEN=${INTERNAL_API_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 384M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18789/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  vi-realtime:
    build:
      context: /opt/vi-agent/repo/realtime
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - API_BASE_URL=http://host.docker.internal:__API_PORT__
      - INTERNAL_API_TOKEN=${INTERNAL_API_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
