# Per-developer vi-agent instance (image pull mode)
# Generated by deploy-instance.sh — do not edit manually
# Developer: __DEV_NAME__
# Slot: __SLOT__
# Image Tag: __IMAGE_TAG__

name: vi-agent-__DEV_NAME__

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: vi___DEV_NAME__
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: vi___DEV_NAME__
    ports:
      - "127.0.0.1:__POSTGRES_PORT__:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vi___DEV_NAME__ -d vi___DEV_NAME__"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - vi-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:__REDIS_PORT__:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} --no-auth-warning ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - vi-network

  api-server:
    image: collov/vi-agent-api-server:__IMAGE_TAG__
    restart: unless-stopped
    ports:
      - "__API_PORT__:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://vi___DEV_NAME__:${POSTGRES_PASSWORD}@postgres:5432/vi___DEV_NAME__
      - POSTGRES_USER=vi___DEV_NAME__
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=vi___DEV_NAME__
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - "REDIS_PREFIX=__DEV_NAME__:"
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRE_MINUTES=1440
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GCS_BUCKET=${GCS_BUCKET:-vi-uploads}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_BASE_URL=http://${SERVER_IP}:__API_PORT__
      - CORS_ORIGINS=http://${SERVER_IP}:__FRONTEND_PORT__,https://${SERVER_IP}:__FRONTEND_HTTPS_PORT__,http://localhost:__FRONTEND_PORT__
      - INTERNAL_API_TOKEN=${INTERNAL_API_TOKEN}
      - FIREBASE_ENABLED=${FIREBASE_ENABLED:-false}
      - FIREBASE_PROJECTS=${FIREBASE_PROJECTS:-}
      - VI_AGENT_NAME=vi-__DEV_NAME__
      - IMAGE_TAG=__IMAGE_TAG__
      - USER_DATA_DIR=/data/users
      - SHARED_SKILLS_DIR=/data/shared/skills
    volumes:
      - api_user_data:/data/users
      - ${FIREBASE_SA_DIR:-./firebase}:/firebase:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 384M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - vi-network

  frontend:
    image: collov/vi-agent-frontend:__IMAGE_TAG__
    restart: unless-stopped
    ports:
      - "__FRONTEND_PORT__:80"
      - "__FRONTEND_HTTPS_PORT__:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      api-server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 192M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - vi-network

  nanoclaw:
    image: collov/vi-agent-nanoclaw:__IMAGE_TAG__
    restart: unless-stopped
    ports:
      - "__NANOCLAW_PORT__:3100"
      - "__NANOCLAW_HTTPS_PORT__:3101"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - API_SERVER_URL=http://api-server:8000
      # USER_ID no longer needed — NanoClaw discovers active users dynamically
      - USER_DATA_DIR=/workspace
      - HEALTH_PORT=3100
      - INTERNAL_API_TOKEN=${INTERNAL_API_TOKEN}
      - DASHBOARD=true
      - SSL_DIR=/etc/nginx/ssl
    volumes:
      - nanoclaw_workspace:/workspace
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      redis:
        condition: service_healthy
      api-server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - vi-network

  vi-realtime:
    image: collov/vi-agent-realtime:__IMAGE_TAG__
    restart: unless-stopped
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - API_BASE_URL=http://api-server:8000
      - INTERNAL_API_TOKEN=${INTERNAL_API_TOKEN}
      - VI_AGENT_NAME=vi-__DEV_NAME__
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1.5G
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - vi-network

volumes:
  postgres_data:
  redis_data:
  nanoclaw_workspace:
  api_user_data:

networks:
  vi-network:
    driver: bridge
