#!/usr/bin/env bash
# sync-board.sh — Generate board.md from GitHub Issues
#
# Usage: ./scripts/sync-board.sh
#
# This script queries GitHub Issues and generates a formatted board.md
# that serves as a read-only view of the team's task status.

set -euo pipefail

BOARD_FILE=".teamspace/board.md"
TEMP_FILE=$(mktemp)

# Check gh auth
if ! gh auth status &>/dev/null; then
  echo "❌ gh CLI not authenticated. Run: gh auth login"
  exit 1
fi

echo "📋 Syncing board.md from GitHub Issues..."

# Fetch all mission-contract issues
ALL_ISSUES=$(gh issue list \
  --label "mission-contract" \
  --state all \
  --json number,title,labels,assignees,state,createdAt,closedAt \
  --limit 200 2>/dev/null)

# Helper: extract issues by status label
issues_by_status() {
  local status="$1"
  echo "$ALL_ISSUES" | jq -r --arg s "status:$status" \
    '[.[] | select(.labels | map(.name) | index($s))]'
}

# Helper: get label value by prefix
get_label() {
  local labels="$1"
  local prefix="$2"
  echo "$labels" | jq -r --arg p "$prefix" \
    '[.[] | .name | select(startswith($p))] | first // ""' | sed "s/^${prefix}//"
}

# Helper: get assignee
get_assignee() {
  echo "$1" | jq -r '.assignees | map(.login) | join(", ") // "—"'
}

# Read version spec for test matrix header
VERSION_SPEC=""
if [ -f ".claude/drive/v0.1-definition/v0.1-spec.md" ]; then
  VERSION_SPEC="V0.1"
fi

# Generate board
cat > "$TEMP_FILE" << 'HEADER'
# VI Agent — Team Board

> ⚠️ **This file is auto-generated by `scripts/sync-board.sh`.**
> Source of truth: [GitHub Issues](../../issues?q=label%3Amission-contract)
> Do NOT edit manually — changes will be overwritten.
>
> Regenerate: `./scripts/sync-board.sh`

---

HEADER

# --- Blocked ---
BLOCKED=$(issues_by_status "blocked")
BLOCKED_COUNT=$(echo "$BLOCKED" | jq 'length')

cat >> "$TEMP_FILE" << EOF
## 🔴 Blocked

| # | Task | Owner | Since |
|---|------|-------|-------|
EOF

if [ "$BLOCKED_COUNT" -gt 0 ]; then
  echo "$BLOCKED" | jq -r '.[] | "| #\(.number) | \(.title) | \(.assignees | map(.login) | join(", ") // "—") | — |"' >> "$TEMP_FILE"
fi

echo "" >> "$TEMP_FILE"

# --- In Progress ---
WIP=$(issues_by_status "wip")
WIP_COUNT=$(echo "$WIP" | jq 'length')

cat >> "$TEMP_FILE" << EOF
## 🟡 In Progress

| # | Task | Owner | Started |
|---|------|-------|---------|
EOF

if [ "$WIP_COUNT" -gt 0 ]; then
  echo "$WIP" | jq -r '.[] | "| #\(.number) | \(.title) | \(.assignees | map(.login) | join(", ") // "—") | \(.createdAt[:10]) |"' >> "$TEMP_FILE"
fi

echo "" >> "$TEMP_FILE"

# --- In Review ---
REVIEW=$(issues_by_status "review")
REVIEW_COUNT=$(echo "$REVIEW" | jq 'length')

cat >> "$TEMP_FILE" << EOF
## 🔵 In Review

| # | Task | Owner |
|---|------|-------|
EOF

if [ "$REVIEW_COUNT" -gt 0 ]; then
  echo "$REVIEW" | jq -r '.[] | "| #\(.number) | \(.title) | \(.assignees | map(.login) | join(", ") // "—") |"' >> "$TEMP_FILE"
fi

echo "" >> "$TEMP_FILE"

# --- Queued ---
QUEUED=$(issues_by_status "queued")
QUEUED_COUNT=$(echo "$QUEUED" | jq 'length')

cat >> "$TEMP_FILE" << EOF
## 📋 Queued

| # | Task | Priority | Size | Domain | Version |
|---|------|----------|------|--------|---------|
EOF

if [ "$QUEUED_COUNT" -gt 0 ]; then
  echo "$QUEUED" | jq -r '.[] |
    {
      num: .number,
      title: .title,
      priority: ([.labels[].name | select(startswith("priority:"))] | first // "" | sub("priority:"; "")),
      size: ([.labels[].name | select(startswith("size:"))] | first // "" | sub("size:"; "")),
      domain: ([.labels[].name | select(startswith("domain:"))] | first // "" | sub("domain:"; "")),
      version: ([.labels[].name | select(startswith("version:"))] | first // "" | sub("version:"; ""))
    } |
    "| #\(.num) | \(.title) | \(.priority) | \(.size) | \(.domain) | \(.version) |"' >> "$TEMP_FILE"
fi

echo "" >> "$TEMP_FILE"

# --- Done (recent, last 20) ---
DONE=$(issues_by_status "done")
DONE_COUNT=$(echo "$DONE" | jq 'length')

cat >> "$TEMP_FILE" << EOF
## ✅ Done (Recent)

| # | Task | Owner | Completed |
|---|------|-------|-----------|
EOF

if [ "$DONE_COUNT" -gt 0 ]; then
  echo "$DONE" | jq -r '.[] | "| #\(.number) | \(.title) | \(.assignees | map(.login) | join(", ") // "—") | \(.closedAt[:10] // "—") |"' | head -20 >> "$TEMP_FILE"
fi

echo "" >> "$TEMP_FILE"

# --- Stats ---
TOTAL_OPEN=$(echo "$ALL_ISSUES" | jq '[.[] | select(.state == "OPEN")] | length')
TOTAL_CLOSED=$(echo "$ALL_ISSUES" | jq '[.[] | select(.state == "CLOSED")] | length')

cat >> "$TEMP_FILE" << EOF
---

## 📊 Stats

| Metric | Count |
|--------|-------|
| Blocked | $BLOCKED_COUNT |
| In Progress | $WIP_COUNT |
| In Review | $REVIEW_COUNT |
| Queued | $QUEUED_COUNT |
| Done | $DONE_COUNT |
| **Total Open** | **$TOTAL_OPEN** |
| **Total Closed** | **$TOTAL_CLOSED** |

---

*Last synced: $(date -u '+%Y-%m-%d %H:%M UTC')*
EOF

# Atomic write
mv "$TEMP_FILE" "$BOARD_FILE"

echo "✅ Board synced: $BOARD_FILE"
echo "   Queued: $QUEUED_COUNT | WIP: $WIP_COUNT | Review: $REVIEW_COUNT | Done: $DONE_COUNT"
